export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_Fail = "USER_SIGNIN_Fail";
export const USER_SIGNOUT = "USER_SIGNOUT";

