const data = {
  products: [
    {
      _id: '1',
      name: 'پیراهن مردانه نایک',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 540000,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'اورجینال با بهترین کیفیت',
    },
    {
      _id: '2',
      name: 'پیراهن مردانه آدیداس',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 580000,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'اورجینال با بهترین کیفیت',
    },
    {
      _id: '3',
      name: 'پیراهن مردانه لاکوست',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 800000,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'اورجینال با بهترین کیفیت',
    },
    {
      _id: '4',
      name: 'شلوار مردانه نایک',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 490000,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'اورجینال با بهترین کیفیت',
    },
    {
      _id: '5',
      name: 'شلوار مردانه پوما',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 630000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'اورجینال با بهترین کیفیت',
    },
    {
      _id: '6',
      name: 'شلوار مردانه آدیداس',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 850000,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'اورجینال با بهترین کیفیت',
    },
  ],
};
export default data;
